# Generated by Django 3.2.13 on 2022-05-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_file',
            field=models.FileField(default='upload/linkin_park_numb.mp3', upload_to='upload/'),
        ),
    ]
